In [1]:
ecoli_path = '/Users/mariavarga/AQM/AQM_SessionMaterial/Weekly_Material/Week_7/data/ecoli.csv'

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import random

In [3]:
ecoli = pd.read_csv(ecoli_path,header=None).dropna()

In [4]:
ecoli.head()

0     1     2     3    4     5     6     7   8
0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35  cp
1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44  cp
2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46  cp
3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36  cp
4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35  cp

In [5]:
ecoli.describe()

1           2           3           4           5           6  \
count  336.000000  336.000000  336.000000  336.000000  336.000000  336.000000   
mean     0.500060    0.500000    0.495476    0.501488    0.500030    0.500179   
std      0.194634    0.148157    0.088495    0.027277    0.122376    0.215751   
min      0.000000    0.160000    0.480000    0.500000    0.000000    0.030000   
25%      0.340000    0.400000    0.480000    0.500000    0.420000    0.330000   
50%      0.500000    0.470000    0.480000    0.500000    0.495000    0.455000   
75%      0.662500    0.570000    0.480000    0.500000    0.570000    0.710000   
max      0.890000    1.000000    1.000000    1.000000    0.880000    1.000000   

                7  
count  336.000000  
mean     0.499732  
std      0.209411  
min      0.000000  
25%      0.350000  
50%      0.430000  
75%      0.710000  
max      0.990000

In [6]:
ecoli.columns = ecoli.columns.astype('str')

In [7]:
X = ecoli.drop(['0','8'],axis =1)
y = ecoli['8']

In [8]:
X = np.array(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Kmeans algorithm

In [74]:
class Kmeans:
    
    def __init__(self, K=2, epsilon=1e-10, max_iter=300, L1=False):
        self.K = K
        self.epsilon = epsilon
        self.max_iter = max_iter
        self.L1 = L1
    
    
    def fit(self,X):
 
        random.seed(3)
        #initiate centroids
        centroids = X[np.random.choice(X.shape[0], self.K, replace=False)]
        # final Cluster
        clusters = np.zeros(len(X)).astype('int')
        # to store the value of centroids when it updates
        C_old = np.zeros(centroids.shape)
        # error func. - Distance between new centroids and old centroids
        #error = 10
        
        #while error > self.epsilon :
        for j in range(self.max_iter):
        
            
            # assigning each value to its closest cluster
            for i in range(len(X)):
                if self.L1:
                    distances = np.sum(abs(X[i] - centroids), axis=1) 
                else:
                    distances = np.linalg.norm(X[i] - centroids, axis=1) 
                clusters[i] = np.argmin(distances)
               
            # storing old centroid 
           # C_old = centroids
          
            
            # finding the new centroids by taking the average value
            for i in range(self.K):
                points = [X[j] for j in range(len(X)) if clusters[j] == i]
                centroids[i] = np.mean(points, axis=0)
              
            #if self.L1:
              #  error = np.sum(abs(C_old - centroids), axis=None) 
           # else:
                #error = np.linalg.norm(C_old - centroids, axis=None) 
               
                
       
        self.clusters = clusters
        self.centroids = centroids
            
    def predict(self,X_test):
        
        clusters = np.zeros(len(X_test)).astype('int')
        # assigning each value to its closest cluster
        for i in range(len(X_test)):
            if self.L1:
                distances = np.sum(abs(X_test[i] - self.centroids), axis=1)
            else:
                distances = np.linalg.norm(X_test[i] - self.centroids, axis=1) 
            cluster = np.argmin(distances)
            clusters[i] = cluster
        #predicted clusters    
        self.predicted = clusters

## Euclidian Distance

In [75]:
kmeans = Kmeans(K=4,epsilon=0)

In [86]:
kmeans.fit(X_train)

In [87]:
kmeans.clusters

array([3, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 0, 3, 0, 1, 1, 0, 3, 3,
       0, 1, 1, 3, 0, 3, 2, 0, 3, 0, 3, 2, 2, 2, 0, 0, 0, 0, 0, 2, 3, 1, 0,
       0, 0, 1, 0, 0, 3, 2, 2, 2, 0, 2, 0, 1, 0, 3, 1, 0, 2, 1, 2, 2, 3, 1,
       3, 1, 2, 3, 0, 0, 1, 0, 2, 3, 2, 1, 0, 3, 0, 1, 0, 1, 3, 3, 0, 1, 2,
       3, 2, 1, 2, 2, 0, 0, 1, 1, 3, 2, 0, 1, 1, 2, 1, 2, 0, 1, 2, 2, 2, 1,
       0, 2, 0, 3, 1, 0, 3, 1, 1, 3, 0, 3, 0, 2, 1, 2, 0, 1, 1, 2, 0, 0, 1,
       1, 3, 2, 0, 0, 2, 0, 1, 3, 1, 1, 1, 3, 1, 0, 1, 2, 2, 3, 2, 0, 0, 2,
       2, 0, 3, 2, 2, 0, 0, 1, 3, 0, 2, 1, 3, 1, 1, 1, 0, 1, 2, 3, 1, 2, 0,
       3, 3, 2, 0, 3, 1, 2, 0, 3, 3, 0, 0, 2, 0, 0, 3, 1, 0, 0, 1, 2, 0, 2,
       0, 2, 3, 2, 0, 1, 0, 3, 3, 1, 1, 2, 1, 0, 3, 3, 2, 1])

In [88]:
kmeans.predict(X_test)

In [89]:
kmeans.predicted

array([3, 1, 2, 3, 2, 3, 0, 2, 2, 3, 0, 1, 1, 3, 3, 0, 0, 0, 1, 3, 0, 1, 1,
       2, 3, 3, 1, 2, 0, 1, 3, 2, 2, 3, 3, 2, 0, 2, 1, 2, 1, 3, 0, 0, 1, 2,
       2, 3, 0, 1, 1, 0, 0, 1, 2, 3, 1, 0, 1, 1, 3, 1, 0, 2, 2, 2, 3, 0, 3,
       0, 2, 2, 3, 1, 1, 3, 2, 0, 3, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0, 2,
       0, 1, 0, 3, 0, 1, 1, 0, 0, 1, 3, 3, 2, 2, 3, 0, 1, 0, 0])

## L1 distance (k-medians)

In [90]:
kmeans = Kmeans(K=4,L1=True)

In [91]:
kmeans.fit(X_train)

In [92]:
kmeans.clusters

array([2, 1, 0, 1, 0, 1, 1, 3, 1, 0, 2, 3, 0, 1, 1, 1, 0, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 3, 1, 2, 3, 1, 2, 1, 2, 3, 3, 3, 1, 1, 1, 1, 1, 3, 2, 0, 1,
       1, 1, 0, 1, 1, 0, 3, 3, 3, 1, 3, 1, 2, 1, 2, 0, 1, 3, 2, 3, 3, 2, 0,
       0, 2, 3, 2, 1, 1, 0, 1, 3, 2, 3, 2, 1, 2, 1, 0, 1, 0, 2, 2, 1, 0, 3,
       2, 3, 0, 3, 3, 1, 1, 0, 2, 0, 3, 1, 0, 2, 3, 2, 3, 1, 0, 3, 3, 3, 0,
       1, 3, 1, 2, 0, 1, 3, 2, 2, 0, 1, 0, 1, 3, 0, 3, 1, 0, 2, 3, 1, 1, 0,
       0, 2, 3, 1, 1, 3, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 3, 3, 2, 3, 1, 1, 2,
       3, 1, 2, 3, 3, 1, 1, 2, 1, 2, 3, 2, 2, 2, 2, 2, 1, 0, 3, 0, 2, 3, 1,
       0, 0, 3, 1, 2, 2, 3, 1, 0, 2, 1, 1, 3, 1, 1, 2, 0, 1, 1, 0, 3, 1, 3,
       1, 3, 2, 3, 1, 2, 1, 2, 2, 2, 0, 3, 0, 1, 0, 2, 3, 0])

In [93]:
kmeans.predict(X_test)

In [94]:
kmeans.predicted

array([2, 0, 3, 0, 3, 2, 1, 3, 3, 2, 1, 2, 0, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0,
       3, 2, 2, 0, 3, 1, 0, 2, 3, 3, 3, 2, 3, 1, 3, 2, 3, 0, 2, 1, 1, 2, 3,
       3, 2, 1, 2, 2, 1, 1, 2, 3, 0, 0, 1, 2, 0, 2, 0, 1, 3, 3, 3, 2, 1, 2,
       1, 3, 3, 2, 0, 0, 2, 3, 1, 2, 0, 1, 1, 2, 2, 2, 1, 1, 3, 2, 1, 1, 3,
       1, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 2, 3, 3, 2, 1, 0, 1, 1])

## Sklearn library

In [95]:
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans

In [96]:
kmeans_sk = KMeans(n_clusters=4, random_state=0)

In [97]:
kmeans_sk.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [98]:
kmeans_sk.labels_

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 0, 0, 0,
       0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 3, 3, 3, 0, 3, 3, 3, 1,
       3, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3, 3, 0, 0, 3, 0, 3, 0, 0, 0, 0, 3, 0,
       0, 0, 3, 3, 0, 2, 1, 1, 1, 1, 2, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 0, 3,
       3, 3, 3, 3, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1,

# hdbscan

In [99]:
import hdbscan

In [100]:
mocap_path = '/Users/mariavarga/AQM/AQM_SessionMaterial/Weekly_Material/Week_7/data/mocap.csv'

In [101]:
mocap = pd.read_csv(mocap_path).dropna()

In [102]:
mocap.head()

Class  User         X0         Y0         Z0         X1         Y1  \
0      0     0   0.000000   0.000000   0.000000   0.000000   0.000000   
1      1     0  54.263880  71.466776 -64.807709  76.895635  42.462500   
2      1     0  56.527558  72.266609 -61.935252  39.135978  82.538530   
3      1     0  55.849928  72.469064 -62.562788  37.988804  82.631347   
4      1     0  55.329647  71.707275 -63.688956  36.561863  81.868749   

          Z1         X2         Y2 ...  Z8 X9 Y9 Z9 X10 Y10 Z10 X11 Y11 Z11  
0   0.000000   0.000000   0.000000 ...   0  0  0  0   0   0   0   0   0   0  
1 -72.780545  36.621229  81.680557 ...   ?  ?  ?  ?   ?   ?   ?   ?   ?   ?  
2 -49.596509  79.223743  43.254091 ...   ?  ?  ?  ?   ?   ?   ?   ?   ?   ?  
3 -50.606259  78.451526  43.567403 ...   ?  ?  ?  ?   ?   ?   ?   ?   ?   ?  
4 -52.752784  86.320630  68.214645 ...   ?  ?  ?  ?   ?   ?   ?   ?   ?   ?  

[5 rows x 38 columns]

In [104]:
mocap.describe()

Class          User            X0            Y0            Z0  \
count  78096.000000  78096.000000  78096.000000  78096.000000  78096.000000   
mean       2.983738      7.959127     50.345664     85.812051    -29.984712   
std        1.421183      4.697810     32.696173     40.204363     34.361918   
min        0.000000      0.000000   -108.552738    -98.233756   -126.770872   
25%        2.000000      5.000000     29.295062     63.494432    -56.356438   
50%        3.000000      9.000000     54.619964     86.526246    -30.864125   
75%        4.000000     12.000000     72.488686    113.107355     -1.418803   
max        5.000000     14.000000    190.017835    169.175464    113.345119   

                 X1            Y1            Z1            X2            Y2  \
count  78096.000000  78096.000000  78096.000000  78096.000000  78096.000000   
mean      49.595209     86.192647    -29.509202     48.612121     83.771315   
std       32.478238     40.453214     34.764398     33.605390     41.023543   
min     -111.685241    -96.142589   -166.006838   -106.886524   -100.789312   
25%       28.755137     64.154529    -57.360107     25.170006     58.052385   
50%       54.215514     87.542751    -30.184005     53.814580     86.458324   
75%       71.762039    116.219398     -0.366692     71.561951    106.660827   
max      188.691997    170.209350    104.697852    188.760168    168.186466   

                 Z2  
count  78096.000000  
mean     -30.560515  
std       35.120329  
min     -129.595296  
25%      -58.654059  
50%      -32.352414  
75%       -0.944786  
max      104.590879

In [105]:
np.unique(mocap['Class'])

array([0, 1, 2, 3, 4, 5])

In [125]:

mocap_sample = mocap.sample(5000)

In [127]:
mocap_sample = mocap_sample[mocap_sample.columns[:20]]

In [128]:
# there are some '?' that needs to be removed 
mocap_sample = mocap_sample.convert_objects(convert_numeric=True).dropna(axis=0)

/Users/mariavarga/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  


In [129]:
X = mocap_sample.drop(['Class','User'],axis=1)
y = mocap_sample['Class']

In [130]:
X.shape

(4110, 18)

In [131]:
clusterer = hdbscan.HDBSCAN(min_cluster_size=5)
cluster_labels = clusterer.fit_predict(X)

In [132]:
cluster_labels

array([ 3,  3,  3, ...,  3,  3, -1])